import MaintenanceDashboard from '@/app/(app)/maintenance-dashboard/[id]';
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'ar';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  translations: Record<Language, Record<string, string>>;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const translations = {
  fr: {
    // Auth & Onboarding
    welcome: "Bienvenue sur ICAR",
    welcomeDesc: "Suivez votre véhicule, gérez les rapports et plus encore.",
    stayInformed: "Restez informé",
    stayInformedDesc: "Recevez des mises à jour et des alertes en temps réel.",
    getStarted: "Commencer",
    continue: "Continuer",
    language: "العربية",
    signup: "Inscription",
    firstName: "Prénom",
    firstNameInput: "Saisie du prénom",
    lastName: "Nom",
    lastNameInput: "Saisie du nom",
    email: "Email",
    emailInput: "Saisie de l'email",
    phone: "Numéro de téléphone",
    phoneInput: "Saisie du numéro de téléphone",
    password: "Mot de passe",
    passwordInput: "Saisie du mot de passe",
    enterprise: "Entreprise",
    personal: "Personnel",
    login: "Se connecter",
    tn: "+216 (Tunisie)",
    dz: "+213 (Algérie)",
    invalidEmail: "Veuillez entrer un email valide",
    invalidCredentials: "Nom d'utilisateur ou mot de passe incorrect",
    invalidPassword: "Le mot de passe doit contenir au moins 8 caractères",
    invalidPhone: "Veuillez entrer un numéro de téléphone valide",
    requiredField: "Ce champ est requis",
    verifyCode: "Vérifier le code",
    enterCode: "Entrez le code à 6 chiffres envoyé par SMS",
    invalidCode: "Veuillez entrer un code valide à 6 chiffres",
    forgotPassword: "Mot de passe oublié ?",
    signupPage: "Créer un compte",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    resetPassword: "Réinitialiser le mot de passe",
    sendCode: "Envoyer le code",
    errorOccurred: "Une erreur est survenue. Veuillez réessayer.",
    verificationCodeInput: "Saisie du code de vérification",
    appLogo: "Logo de l'application",
    appName: "Suite ICAR",
    back: "Retour",
    MaintenanceDashboard: "Tableau de bord de maintenance",

    // Dashboard
    dashboard: "Tableau de bord",
    hello: "Bonjour",
    welcomeBack: "Bon retour !",
    online: "En ligne",
    defaultUser: "Utilisateur",
    defaultEmail: "utilisateur@exemple.com",
    manageVehicles: "Gérez vos véhicules et services",
    myCars: "Mes voitures Disponibles",
    seeAll: "Voir tout",
    noCarsAdded: "Aucune voiture ajoutée",
    addFirstCar: "Commencez par ajouter votre première voiture pour suivre sa maintenance et ses services",
    addYourFirstCar: "Ajouter votre première voiture",
    cars: "Voitures",
    services: "Services",
    pending: "En attente",
    vehicles: "véhicules",
    addVehicle: "Ajouter un véhicule",
    yesterday: "Hier",
    daysAgo: "jours",
    noRecentActivity: "Aucune activité récente",
    startByBookingService: "Commencez par réserver un service pour votre voiture",
    scheduleService: "chez IREPAIR",
    orderParts: "Commander maintenant",

    // Car Management
    addNewCar: "Ajouter une nouvelle voiture",
    manualEntry: "Saisie manuelle",
    qrCode: "Code QR",
    brand: "Marque",
    selectBrand: "Sélectionner la marque",
    model: "Modèle",
    selectModel: "Sélectionner le modèle",
    vinCode: "Code VIN",
    enterVin: "Entrer le code VIN",
    fuelType: "Type de carburant",
    selectFuelType: "Sélectionner le type de carburant",
    registrationType: "Type d'immatriculation",
    selectRegistrationType: "Sélectionner le type d'immatriculation",
    registrationNumber: "Numéro d'immatriculation",
    enterRegistrationNumber: "Entrer le numéro d'immatriculation",
    mileage: "Kilométrage",
    enterMileage: "Entrer le kilométrage actuel",
    firstRegistrationDate: "Date de première immatriculation",
    addCar: "Ajouter la voiture",
    scanQrCode: "Scanner le code QR",
    scanQrDesc: "Ajoutez rapidement votre voiture en scannant son code QR. Cela remplira automatiquement toutes les informations du véhicule.",
    openQrScanner: "Ouvrir le scanner QR",
    carteGrise: "Carte Grise",
    scanCarteGrise: "Scanner Carte Grise",
    scanCarteGriseDesc: "Prenez des photos du recto et verso de votre carte grise. Notre IA extraira automatiquement les informations du véhicule.",
    openCarteGriseScanner: "Ouvrir le scanner de documents",
    scanCarteGriseRecto: "Scanner Carte Grise (Recto)",
    scanCarteGriseVerso: "Scanner Carte Grise (Verso)",
    processing: "Traitement en cours...",
    processingImages: "Traitement des images...",
    ocrProcessingDesc: "Notre IA extrait les informations du véhicule à partir de vos images de carte grise.",
    scanRectoInstructions: "Positionnez le recto de votre carte grise",
    scanRectoDesc: "Assurez-vous que tout le texte est clairement visible et que le document est bien éclairé",
    scanVersoInstructions: "Positionnez le verso de votre carte grise",
    scanVersoDesc: "Assurez-vous que le verso est clairement visible et bien éclairé",
    takePhoto: "Prendre une photo",
    chooseFromGallery: "Choisir dans la galerie",
    retake: "Reprendre",
    ocrSuccessTitle: "Traitement OCR terminé",
    ocrSuccessMessage: "Les informations du véhicule ont été extraites avec succès. Veuillez vérifier et confirmer.",
    review: "Vérifier",
    extractedData: "Données extraites",

    // Car Profile
    carDetails: "Détails de la voiture",
    basicInformation: "Informations de base",
    serviceInformation: "Informations de service",
    lastService: "Dernier service",
    nextService: "Prochain service",
    addedToApp: "Ajouté à l'app",
    noServiceRecorded: "Aucun service enregistré",
    notScheduled: "Non programmé",
    quickActions: "Actions rapides",
    edit: "Modifier",
    export: "Générer le QR Code",
    share: "Partager",
    delete: "Supprimer",
    serviceHistory: "Historique des services",
    noServiceHistory: "Aucun historique de service disponible",
    serviceHistoryDesc: "Les enregistrements de service apparaîtront ici une fois que vous commencerez à utiliser nos services",
    requestService: "Demander un service",
    garage: "Garage",
    cost: "Coût",
    notes: "Notes",
    unknownCar: "Voiture inconnue",
    unknownGarage: "Garage inconnu",
    unknownService: "Service inconnu",
    accepted: "Accepté",
    inProgress: "En cours",
    completed: "Terminé",
    cancelled: "Annulé",

    // Service Booking
    bookService: "Réserver un service",
    selectService: "Sélectionner un service",
    selectDate: "Sélectionner la date",
    selectTime: "Sélectionner l'heure",
    selectMechanic: "Sélectionner un mécanicien",
    serviceType: "Type de service",
    appointmentDate: "Date du rendez-vous",
    appointmentTime: "Heure du rendez-vous",
    mechanic: "Mécanicien",
    bookAppointment: "Réserver le rendez-vous",
    serviceBooked: "Service réservé",
    serviceBookedDesc: "Votre rendez-vous a été réservé avec succès",
    
    // Service Categories & Details
    basicService: "Service de base / intérimaire",
    fullService: "Service complet / majeur",
    manufacturerService: "Service constructeur / programmé",
    engineDiagnostic: "Service de diagnostic moteur",
    carDetailing: "Détaillage auto / Service de nettoyage",
    acService: "Service de climatisation",
    transmissionService: "Service de transmission",
    brakeService: "Service de freinage",
    tireService: "Service pneus et alignement",
    batteryService: "Service de batterie",
    
    chooseServiceType: "Choisir le type de service",
    chooseMechanicService: "Choisir le mécanicien et le service",
    chooseDateTimeService: "Choisir la date et l'heure",
    confirmBookingService: "Confirmer la réservation",
    
    paymentMethod: "Méthode de paiement",
    cash: "Espèces",
    card: "Carte",
    bookingDetails: "Détails de la réservation",
    total: "Total",
    
    next: "Suivant",
    booking: "Réservation...",
    confirmBooking: "Confirmer",
    
    includes: "Inclut:",
    noServicesAvailable: "Aucun service disponible",

    // Maps & Mechanics
    findMechanics: "Trouver mécaniciens",
    nearbyMechanics: "Mécaniciens à proximité",
    mechanicProfile: "Profil du mécanicien",
    rating: "Note",
    distance: "Distance",
    openNow: "Ouvert maintenant",
    closed: "Fermé",
    viewProfile: "Voir le profil",
    getDirections: "Obtenir l'itinéraire",
    callMechanic: "Appeler le mécanicien",
    // Spare Parts
    spareParts: "Commander Des pièces",
    categories: "Catégories",
    parts: "Pièces",
    seller: "Vendeur",
    viewDetails: "Voir les détails",
    noPartsAvailable: "Aucune pièce disponible pour cette catégorie.",
    partNotFound:"Pièce non trouvée",
    partDetails: "Détails de la pièce",
    name: "Nom",
    category: "Catégorie",
    price: "Prix",
    description: "Description",
    sellerInformation:"Informations du vendeur",
    contact:"Contact",
    purchase: "Acheter",
    // Profile & Settings
    profile: "Profil",
    editProfile: "Modifier le profil",
    settings: "Paramètres",
    notifications: "Notifications",
    helpSupport: "Aide et support",
    logout: "Déconnexion",
    personalInfo: "Informations personnelles",
    accountSettings: "Paramètres du compte",
    appSettings: "Paramètres de l'application",
    languageSettings: "Langue",
    theme: "Thème",
    pushNotifications: "Notifications push",
    emailNotifications: "Notifications par email",
    changePassword: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    enterCurrentPassword: "Saisir le mot de passe actuel",
    enterNewPassword: "Saisir le nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    passwordsDontMatch: "Les mots de passe ne correspondent pas",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
    passwordUpdated: "Mot de passe mis à jour avec succès",
    errorUpdatingPassword: "Erreur lors de la mise à jour du mot de passe",

    // Common
    save: "Enregistrer",
    cancel: "Annuler",
    ok: "OK",
    yes: "Oui",
    no: "Non",
    loading: "Chargement...",
    success: "Succès",
    error: "Erreur",
    warning: "Avertissement",
    info: "Information",
    retry: "Réessayer",
    close: "Fermer",
    search: "Rechercher",
    filter: "Filtrer",
    sort: "Trier",
    refresh: "Actualiser",
    noPhoneNumber: "Aucun numéro de téléphone disponible pour ce garage.",
    cannotMakeCall: "Impossible de passer des appels sur cet appareil.",
    callError: "Une erreur s'est produite lors de l'appel.",
    carProfile: "Profil du véhicule",
    noCarData: "Aucune donnée de véhicule disponible",
    vin: "VIN / Le numéro de châssis",
    firstRegistration: "Première immatriculation",
    dateAdded: "Date d'ajout",
    immatriculationType: "Type d'immatriculation",
    registrationSubtype: "Sous-type d'immatriculation",
    carActions: "Actions du véhicule",
    editCar: "Modifier le véhicule",
    exportQrCode: "Exporter le QR Code",
    generatingQr: "Génération du QR Code...",
    qrCodeInstructions: "Scannez ce QR code pour transférer la propriété ou partager les détails",
    shareQrCode: "Partager le QR Code",
    failedToLoadCar: "Impossible de charger les détails du véhicule",
    failedToGenerateQr: "Impossible de générer le QR code",
    failedToShare: "Impossible de partager les détails du véhicule",
    failedToUpdateCar: "Impossible de mettre à jour le véhicule",
    failedToDeleteCar: "Impossible de supprimer le véhicule",
    carUpdated: "Véhicule mis à jour avec succès",
    carDeleted: "Véhicule supprimé avec succès",
    deleteConfirmation: "Supprimer le véhicule",
    deleteConfirmationMessage: "Êtes-vous sûr de vouloir supprimer ce véhicule ?",
    none: "Aucun",
    enterDate: "JJ/MM/AAAA",
    wrongCredentialsOrNotSignedUp: "Identifiants incorrects ou vous n'êtes pas inscrit.",
    
    // Additional Dashboard translations
    quickAccess: "Accès rapide",
    promotions: "Promotions",
    recentActivity: "Activité récente",
    savings: "Économies",
    oilChangeCompleted: "Vidange terminée",
    inspectionDueSoon: "Inspection due bientôt",
    toyotaCamryDaysAgo: "Toyota Camry • Il y a 2 jours",
    hondaCivicInDays: "Honda Civic • Dans 5 jours",
    specialOffer: "Offre spéciale",
    saveUpTo30: "Économisez jusqu'à 30% sur les services",
    new: "NOUVEAU",
    partsRequests: "Demandes de pièces",
    conversations: "Messages",
    
    // Parts Request Screen
    requestPart: "Demander une pièce de rechange",
    selectPartType: "Sélectionner le type de pièce",
    selectVehicle: "Sélectionner le véhicule",
    selectCar: "Sélectionner la voiture",
    selectCarFirst: "Veuillez d'abord sélectionner une voiture",
    choosePart: "Choisir une pièce ",
    chooseCar: "Choisir une voiture",
    quantity: "Quantité",
    urgency: "Urgence",
    low: "Faible",
    medium: "Moyen",
    high: "Élevé",
    additionalNotes: "Notes supplémentaires",
    additionalInfo: "Informations supplémentaires...",
    createRequest: "Créer la demande",
    requestHelpText: "Après avoir soumis votre demande, les fournisseurs de pièces seront informés et pourront vous contacter via le système de messagerie avec des devis et la disponibilité.",
    common: "Commun",
    all: "Tout",
    selectPartTypeDesc: "Choisissez le type de pièce de rechange dont vous avez besoin",
    inStock: "En stock",
    loadingParts: "Chargement des pièces...",
    requestCreated: "Demande créée",
    requestCreatedMessage: "Votre demande de pièce a été créée avec succès. Les fournisseurs de pièces peuvent maintenant vous contacter.",
    sessionExpired: "Session expirée",
    sessionExpiredMessage: "Veuillez vous reconnecter pour continuer.",
    invalidRequest: "Demande invalide",
    invalidRequestMessage: "Veuillez vérifier vos informations et réessayer.",
    partNotFoundMessage: "La pièce sélectionnée n'est plus disponible.",
    unableToCreateRequest: "Impossible de créer la demande",
    unableToCreateRequestMessage: "Impossible de créer la demande. Veuillez réessayer.",
    
    // Mechanic Profile Screen
    mechanicNotFound: "Mécanicien introuvable",
    contactInfo: "Informations de contact",
    location: "Localisation",
    address: "Adresse",
    zone: "Zone",
    verified: "Vérifié",
    call: "Appeler",
    sendEmail: "Envoyer un email",
    callNow: "Appeler maintenant",
    
    // Create Parts Request - Additional translations
    selectCarOrVin: "Veuillez sélectionner une voiture ou saisir le VIN manuellement",
    selectCategory: "Sélectionner une catégorie",
    selectSubCategory: "Sélectionner une sous-catégorie",
    selectItem: "Sélectionner un article",
    addPhoto: "Ajouter une photo (optionnel)",
    addPhotoOptional: "Ajouter une photo (optionnel)",
    photoAdded: "Photo ajoutée",
    tapToAddPhoto: "Appuyez pour ajouter une photo",
    camera: "Caméra",
    gallery: "Galerie",
    skipPhoto: "Ignorer la photo",
    done: "Terminé",
    enterVinManually: "Saisir le VIN manuellement",
    manualVin: "VIN manuel",
    orEnterVinManually: "Ou saisir le VIN manuellement",
    enterVin17Chars: "Saisir le VIN (17 caractères)",
    vinManuallyDesc: "Si vous n'avez pas votre véhicule enregistré, veuillez saisir le numéro VIN manuellement :",
    confirm: "Confirmer",
    chooseCategory: "Choisir une catégorie",
    chooseSubCategory: "Choisir une sous-catégorie",
    chooseItem: "Choisir un article",
    subCategory: "Sous-catégorie",
    item: "Article",
    uploadingImage: "Téléchargement de l'image...",
    photoHelpText: "Souhaitez-vous ajouter une photo de la pièce dont vous avez besoin ? Cela aide les fournisseurs à fournir de meilleurs devis.",
    loadingCategories: "Chargement des catégories...",
    loadingSubcategories: "Chargement des sous-catégories...",
    loadingItems: "Chargement des articles...",
    noCategoriesFound: "Aucune catégorie trouvée",
    noSubcategoriesFound: "Aucune sous-catégorie trouvée",
    noItemsFound: "Aucun article trouvé",
    tapToChangePhoto: "Appuyez pour changer ou supprimer la photo",
    
    // Fuel Tracking
    fuelTracking: "Suivi Carburant",
    fuelHistory: "Historique des pleins",
    addFuelEntry: "Ajouter Versement de carburant",
    noFuelEntries: "Aucun Versement de carburant",
    addFirstFuelEntry: "Commencez par ajouter votre premier plein",
    currentMileage: "Kilométrage actuel",
    statistics: "Statistiques",
    avgConsumption: "Consommation moyenne",
    avgCostPerKm: "Coût moyen par km",
    totalDistance: "Distance totale",
    odometerReading: "Kilométrage compteur",
    enterOdometerReading: "Entrez le kilométrage",
    fuelQuantity: "Quantité de carburant",
    enterFuelQuantity: "Entrez la quantité",
    pricePerLiter: "Prix par litre",
    enterPricePerLiter: "Entrez le prix par litre",
    fuelStation: "Station service",
    drivingConditions: "Conditions de conduite",
    consumption: "Conso",
    add: "Ajouter",
  },
  ar: {
    welcome: "مرحبًا بكم في ICAR",
    welcomeDesc: "تتبع مركبتك، وإدارة التقارير والمزيد.",
    stayInformed: "ابقَ على اطلاع",
    stayInformedDesc: "تلقَ التحديثات والتنبيهات في الوقت الحقيقي.",
    getStarted: "ابدأ",
    continue: "متابعة",
    language: "Français",
    signup: "التسجيل",
    firstName: "الاسم الأول",
    firstNameInput: "إدخال الاسم الأول",
    lastName: "الاسم الأخير",
    lastNameInput: "إدخال الاسم الأخير",
    email: "البريد الإلكتروني",
    emailInput: "إدخال البريد الإلكتروني",
    phone: "رقم الهاتف",
    phoneInput: "إدخال رقم الهاتف",
    password: "كلمة المرور",
    passwordInput: "إدخال كلمة المرور",
    enterprise: "مؤسسة",
    personal: "شخصي",
    login: "تسجيل الدخول",
    tn: "+216 (تونس)",
    dz: "+213 (الجزائر)",
    invalidEmail: "الرجاء إدخال بريد إلكتروني صالح",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
    invalidPassword: "يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل",
    invalidPhone: "الرجاء إدخال رقم هاتف صالح",
    requiredField: "هذا الحقل مطلوب",
    verifyCode: "تحقق من الرمز",
    enterCode: "أدخل الرمز المكون من 6 أرقام المرسل عبر SMS",
    invalidCode: "الرجاء إدخال رمز صالح مكون من 6 أرقام",
    forgotPassword: "هل نسيت كلمة المرور؟",
    signupPage: "إنشاء حساب",
    newPassword: "كلمة مرور جديدة",
    confirmPassword: "تأكيد كلمة المرور",
    resetPassword: "إعادة تعيين كلمة المرور",
    sendCode: "إرسال الرمز",
    errorOccurred: "حدث خطأ. الرجاء المحاولة مرة أخرى.",
    verificationCodeInput: "إدخال رمز التحقق",
    appLogo: "شعار التطبيق",
    appName: "مجموعة ICAR",
back: "رجوع",

    // Dashboard
    dashboard: "لوحة التحكم",
    hello: "مرحباً",
    welcomeBack: "مرحباً !",
    online: "متصل",
    defaultUser: "المستخدم",
    defaultEmail: "user@example.com",
    manageVehicles: "إدارة مركباتك وخدماتك",
    myCars: "سياراتي",
    seeAll: "عرض الكل",
    noCarsAdded: "لم يتم إضافة أي سيارة",
    addFirstCar: "ابدأ بإضافة سيارتك الأولى لتتبع صيانتها وخدماتها",
    addYourFirstCar: "أضف سيارتك الأولى",
    cars: "السيارات",
    services: "الخدمات",
    pending: "قيد الانتظار",
    vehicles: "المركبات",
    addVehicle: "إضافة مركبة",
    yesterday: "الأمس",
    daysAgo: "أيام مضت",
    noRecentActivity: "لا توجد أنشطة حديثة",
    startByBookingService: "ابدأ بحجز خدمة لسيارتك",
    scheduleService: "جدولة الصيانة",
    orderParts: "طلب قطع",

    // Car Management
    addNewCar: "إضافة سيارة جديدة",
    manualEntry: "إدخال يدوي",
    qrCode: "رمز QR",
    brand: "الماركة",
    selectBrand: "اختر الماركة",
    model: "الموديل",
    selectModel: "اختر الموديل",
    vinCode: "رمز VIN",
    enterVin: "أدخل رمز VIN",
    fuelType: "نوع الوقود",
    selectFuelType: "اختر نوع الوقود",
    registrationType: "نوع التسجيل",
    selectRegistrationType: "اختر نوع التسجيل",
    registrationNumber: "رقم التسجيل",
    enterRegistrationNumber: "أدخل رقم التسجيل",
    mileage: "المسافة المقطوعة",
    enterMileage: "أدخل المسافة المقطوعة الحالية",
    firstRegistrationDate: "تاريخ التسجيل الأول",
    addCar: "إضافة السيارة",
    scanQrCode: "مسح رمز QR",
    scanQrDesc: "أضف سيارتك بسرعة عن طريق مسح رمز QR الخاص بها. سيؤدي هذا إلى ملء جميع معلومات المركبة تلقائياً.",
    openQrScanner: "فتح ماسح QR",
    carteGrise: "بطاقة التسجيل",
    scanCarteGrise: "مسح بطاقة التسجيل",
    scanCarteGriseDesc: "التقط صوراً للوجه الأمامي والخلفي لبطاقة تسجيل سيارتك. سيقوم الذكاء الاصطناعي لدينا باستخراج معلومات المركبة تلقائياً.",
    openCarteGriseScanner: "فتح ماسح المستندات",
    scanCarteGriseRecto: "مسح بطاقة التسجيل (الوجه الأمامي)",
    scanCarteGriseVerso: "مسح بطاقة التسجيل (الوجه الخلفي)",
    processing: "جاري المعالجة...",
    processingImages: "معالجة الصور...",
    ocrProcessingDesc: "يقوم الذكاء الاصطناعي لدينا باستخراج معلومات المركبة من صور بطاقة التسجيل الخاصة بك.",
    scanRectoInstructions: "ضع الوجه الأمامي لبطاقة التسجيل",
    scanRectoDesc: "تأكد من أن جميع النصوص مرئية بوضوح وأن المستند مضاء جيداً",
    scanVersoInstructions: "ضع الوجه الخلفي لبطاقة التسجيل",
    scanVersoDesc: "تأكد من أن الوجه الخلفي مرئي بوضوح ومضاء جيداً",
    takePhoto: "التقاط صورة",
    chooseFromGallery: "اختيار من المعرض",
    retake: "إعادة التقاط",
    ocrSuccessTitle: "اكتملت معالجة OCR",
    ocrSuccessMessage: "تم استخراج معلومات المركبة بنجاح. يرجى المراجعة والتأكيد.",
    review: "مراجعة",
    extractedData: "البيانات المستخرجة",

    // Car Profile
    carDetails: "تفاصيل السيارة",
    basicInformation: "المعلومات الأساسية",
    serviceInformation: "معلومات الخدمة",
    lastService: "آخر خدمة",
    nextService: "الخدمة التالية",
    addedToApp: "أضيف للتطبيق",
    noServiceRecorded: "لا توجد خدمة مسجلة",
    notScheduled: "غير مجدولة",
    quickActions: "إجراءات سريعة",
    edit: "تعديل",
    export: "تصدير QR",
    share: "مشاركة",
    delete: "حذف",
    serviceHistory: "تاريخ الخدمات",
    noServiceHistory: "لا يوجد تاريخ خدمات متاح",
    serviceHistoryDesc: "ستظهر سجلات الخدمة هنا بمجرد البدء في استخدام خدماتنا",
    requestService: "طلب خدمة",
    garage: "الورشة",
    cost: "التكلفة",
    notes: "ملاحظات",
    unknownCar: "سيارة غير معروفة",
    unknownGarage: "ورشة غير معروفة",
    unknownService: "خدمة غير معروفة",
    accepted: "مقبول",
    inProgress: "قيد التنفيذ",
    completed: "مكتمل",
    cancelled: "ملغى",
    MaintenanceDashboard: "لوحة معلومات الصيانة",
    // Service Booking
    bookService: "حجز خدمة",
    selectService: "اختر الخدمة",
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    selectMechanic: "اختر الميكانيكي",
    serviceType: "نوع الخدمة",
    appointmentDate: "تاريخ الموعد",
    appointmentTime: "وقت الموعد",
    mechanic: "الميكانيكي",
    bookAppointment: "حجز الموعد",
    serviceBooked: "تم حجز الخدمة",
    serviceBookedDesc: "تم حجز موعدك بنجاح",
    
    // Service Categories & Details
    basicService: "خدمة أساسية / مؤقتة",
    fullService: "خدمة كاملة / رئيسية",
    manufacturerService: "خدمة الصانع / المجدولة",
    engineDiagnostic: "خدمة تشخيص المحرك",
    carDetailing: "تفصيل السيارة / خدمة التنظيف",
    acService: "خدمة تكييف الهواء",
    transmissionService: "خدمة ناقل الحركة",
    brakeService: "خدمة الفرامل",
    tireService: "خدمة الإطارات والمحاذاة",
    batteryService: "خدمة البطارية",
    
    chooseServiceType: "اختر نوع الخدمة",
    chooseMechanicService: "اختر الميكانيكي والخدمة",
    chooseDateTimeService: "اختر التاريخ والوقت",
    confirmBookingService: "تأكيد الحجز",
    
    paymentMethod: "طريقة الدفع",
    cash: "نقد",
    card: "بطاقة",
    bookingDetails: "تفاصيل الحجز",
    total: "المجموع",
    
    next: "التالي",
    booking: "جاري الحجز...",
    confirmBooking: "تأكيد الحجز",
    
    includes: "يشمل:",
    noServicesAvailable: "لا توجد خدمات متاحة",

    // Maps & Mechanics
    findMechanics: "العثور على الميكانيكيين",
    nearbyMechanics: "الميكانيكيون القريبون",
    mechanicProfile: "ملف الميكانيكي",
    rating: "التقييم",
    distance: "المسافة",
    openNow: "مفتوح الآن",
    closed: "مغلق",
    viewProfile: "عرض الملف الشخصي",
    getDirections: "الحصول على الاتجاهات",
    callMechanic: "اتصل بالميكانيكي",
    //Spare Parts
    spareParts: "قطع الغيار",
    categories: "الفئات",
    parts: "القطع",
    seller: "البائع",
    viewDetails: "عرض التفاصيل",
    noPartsAvailable: "لا توجد قطع متاحة لهذا القسم.",
    partNotFound: "القطعة غير موجودة",
    partDetails: "تفاصيل القطعة",
    name: "الاسم",
    category: "الفئة",
    price: "السعر",
    description: "الوصف",
    noPartsFound: "لا توجد قطع متاحة",
    sellerInformation: "معلومات البائع",
    contact:"الاتصال",
    purchase:"شراء",
    
    // Profile & Settings
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف الشخصي",
    settings: "الإعدادات",
    notifications: "الإشعارات",
    helpSupport: "المساعدة والدعم",
    logout: "تسجيل الخروج",
    personalInfo: "المعلومات الشخصية",
    accountSettings: "إعدادات الحساب",
    appSettings: "إعدادات التطبيق",
    languageSettings: "اللغة",
    theme: "المظهر",
    pushNotifications: "الإشعارات الفورية",
    emailNotifications: "إشعارات البريد الإلكتروني",
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    enterCurrentPassword: "أدخل كلمة المرور الحالية",
    enterNewPassword: "أدخل كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    passwordsDontMatch: "كلمتا المرور غير متطابقتين",
    passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    passwordUpdated: "تم تحديث كلمة المرور بنجاح",
    errorUpdatingPassword: "حدث خطأ أثناء تحديث كلمة المرور",

    // Common
    save: "حفظ",
    cancel: "إلغاء",
    ok: "موافق",
    yes: "نعم",
    no: "لا",
    loading: "جاري التحميل...",
    success: "نجح",
    error: "خطأ",
    warning: "تحذير",
    info: "معلومات",
    retry: "إعادة المحاولة",
    close: "إغلاق",
    search: "بحث",
    filter: "تصفية",
    sort: "ترتيب",
    refresh: "تحديث",
    noPhoneNumber: "لا يوجد رقم هاتف متاح لهذه الورشة.",
    cannotMakeCall: "لا يمكن إجراء مكالمات على هذا الجهاز.",
    callError: "حدث خطأ أثناء محاولة الاتصال.",
    carProfile: "ملف السيارة",
    noCarData: "لا توجد بيانات متاحة للسيارة",
    vin: "رقم الهيكل",
    firstRegistration: "تاريخ التسجيل الأول",
    dateAdded: "تاريخ الإضافة",
    immatriculationType: "نوع التسجيل",
    registrationSubtype: "نوع التسجيل الفرعي",
    carActions: "إجراءات السيارة",
    editCar: "تعديل السيارة",
    exportQrCode: "تصدير رمز الاستجابة السريعة",
    generatingQr: "جاري إنشاء رمز الاستجابة السريعة...",
    qrCodeInstructions: "امسح رمز الاستجابة السريعة هذا لنقل الملكية أو مشاركة التفاصيل",
    shareQrCode: "مشاركة رمز الاستجابة السريعة",
    failedToLoadCar: "تعذر تحميل تفاصيل السيارة",
    failedToGenerateQr: "تعذر إنشاء رمز الاستجابة السريعة",
    failedToShare: "تعذر مشاركة تفاصيل السيارة",
    failedToUpdateCar: "تعذر تحديث السيارة",
    failedToDeleteCar: "تعذر حذف السيارة",
    carUpdated: "تم تحديث السيارة بنجاح",
    carDeleted: "تم حذف السيارة بنجاح",
    deleteConfirmation: "حذف السيارة",
    deleteConfirmationMessage: "هل أنت متأكد أنك تريد حذف هذه السيارة؟",
    none: "لا شيء",
    enterRegistration: "أدخل رقم التسجيل",
    enterDate: "يوم/شهر/سنة",
    wrongCredentialsOrNotSignedUp: "بيانات الدخول غير صحيحة أو لم تقم بالتسجيل.",
    
    // Additional Dashboard translations
    quickAccess: "الوصول السريع",
    promotions: "العروض الترويجية",
    recentActivity: "النشاط الأخير",
    savings: "الوفورات",
    oilChangeCompleted: "تم إنجاز تغيير الزيت",
    inspectionDueSoon: "الفحص مطلوب قريباً",
    toyotaCamryDaysAgo: "تويوتا كامري • منذ يومين",
    hondaCivicInDays: "هوندا سيفيك • خلال 5 أيام",
    specialOffer: "عرض خاص",
    saveUpTo30: "وفر حتى 30% على الخدمات",
    new: "جديد",
    partsRequests: "طلبات القطع",
    conversations: "الرسائل",
    
    // Parts Request Screen
    requestPart: "طلب قطعة غيار",
    selectPartType: "اختر نوع القطعة",
    selectVehicle: "اختر المركبة",
    selectCar: "اختر السيارة",
    selectCarFirst: "الرجاء اختيار سيارة أولاً",
    choosePart: "اختر قطعة غيار",
    chooseCar: "اختر سيارة",
    quantity: "الكمية",
    urgency: "الأولوية",
    low: "منخفضة",
    medium: "متوسطة",
    high: "عالية",
    additionalNotes: "ملاحظات إضافية",
    additionalInfo: "معلومات إضافية...",
    createRequest: "إنشاء الطلب",
    requestHelpText: "بعد إرسال طلبك، سيتم إشعار موردي القطع ويمكنهم الاتصال بك من خلال نظام الرسائل مع عروض الأسعار والتوفر.",
    common: "شائع",
    all: "الكل",
    selectPartTypeDesc: "اختر نوع قطعة الغيار التي تحتاجها",
    inStock: "متوفر",
    loadingParts: "جاري تحميل القطع...",
    requestCreated: "تم إنشاء الطلب",
    requestCreatedMessage: "تم إنشاء طلب قطعة الغيار بنجاح. يمكن لموردي القطع الآن الاتصال بك.",
    sessionExpired: "انتهت الجلسة",
    sessionExpiredMessage: "الرجاء تسجيل الدخول مرة أخرى للمتابعة.",
    invalidRequest: "طلب غير صالح",
    invalidRequestMessage: "الرجاء التحقق من معلوماتك وإعادة المحاولة.",
    partNotFoundMessage: "القطعة المحددة لم تعد متاحة.",
    unableToCreateRequest: "تعذر إنشاء الطلب",
    unableToCreateRequestMessage: "تعذر إنشاء الطلب. الرجاء إعادة المحاولة.",
    outOfStock: "غير متوفر",
    limited: "مخزون محدود",
    
    // Mechanic Profile Screen
    mechanicNotFound: "الميكانيكي غير موجود",
    contactInfo: "معلومات الاتصال",
    location: "الموقع",
    address: "العنوان",
    zone: "المنطقة",
    verified: "مُتحقق",
    call: "اتصال",
    sendEmail: "إرسال بريد إلكتروني",
    callNow: "اتصل الآن",
    
    // Create Parts Request - Additional translations
    selectCarOrVin: "الرجاء اختيار سيارة أو إدخال رقم VIN يدوياً",
    selectCategory: "اختر الفئة",
    selectSubCategory: "اختر الفئة الفرعية",
    selectItem: "اختر العنصر",
    addPhoto: "أضف صورة (اختياري)",
    addPhotoOptional: "أضف صورة (اختياري)",
    photoAdded: "تمت إضافة الصورة",
    tapToAddPhoto: "اضغط لإضافة صورة",
    camera: "الكاميرا",
    gallery: "المعرض",
    skipPhoto: "تخطي الصورة",
    done: "تم",
    enterVinManually: "أدخل رقم VIN يدوياً",
    manualVin: "رقم VIN يدوي",
    orEnterVinManually: "أو أدخل رقم VIN يدوياً",
    enterVin17Chars: "أدخل رقم VIN (17 حرفاً)",
    vinManuallyDesc: "إذا لم تكن مركبتك مسجلة، يرجى إدخال رقم VIN يدوياً:",
    confirm: "تأكيد",
    chooseCategory: "اختر فئة",
    chooseSubCategory: "اختر فئة فرعية",
    chooseItem: "اختر عنصر",
    subCategory: "الفئة الفرعية",
    item: "العنصر",
    uploadingImage: "جاري رفع الصورة...",
    photoHelpText: "هل تريد إضافة صورة للقطعة التي تحتاجها؟ هذا يساعد الموردين في تقديم عروض أسعار أفضل.",
    loadingCategories: "جاري تحميل الفئات...",
    loadingSubcategories: "جاري تحميل الفئات الفرعية...",
    loadingItems: "جاري تحميل العناصر...",
    noCategoriesFound: "لا توجد فئات",
    noSubcategoriesFound: "لا توجد فئات فرعية",
    noItemsFound: "لا توجد عناصر",
    tapToChangePhoto: "اضغط لتغيير أو إزالة الصورة",
    
    // Fuel Tracking
    fuelTracking: "تتبع الوقود",
    fuelHistory: "تاريخ التزويد بالوقود",
    addFuelEntry: "إضافة تزويد بالوقود",
    noFuelEntries: "لا توجد سجلات تزويد بالوقود",
    addFirstFuelEntry: "ابدأ بإضافة أول تزويد بالوقود",
    currentMileage: "الكيلومترات الحالية",
    statistics: "الإحصائيات",
    avgConsumption: "الاستهلاك المتوسط",
    avgCostPerKm: "التكلفة المتوسطة لكل كيلومتر",
    totalDistance: "المسافة الإجمالية",
    odometerReading: "قراءة العداد",
    enterOdometerReading: "أدخل قراءة العداد",
    fuelQuantity: "كمية الوقود",
    enterFuelQuantity: "أدخل الكمية",
    pricePerLiter: "السعر لكل لتر",
    enterPricePerLiter: "أدخل السعر لكل لتر",
    fuelStation: "محطة الوقود",
    drivingConditions: "ظروف القيادة",
    consumption: "الاستهلاك",
    add: "إضافة",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');
  const toggleLanguage = () => setLanguage(language === 'fr' ? 'ar' : 'fr');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};